apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
spec:
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  project: default
  source:
    path: values/dataops/mlflow
    repoURL:https://github.com/tuancamtbtx/dataops-argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true