defaultAirflowTag: "2.8.3"
airflowVersion: "2.8.3"

# Airflow database migration job settings
migrateDatabaseJob:
  enabled: true
  # Limit the lifetime of the job object after it finished execution.
  ttlSecondsAfterFinished: 300
  # Command to use when running the migrate database job (templated).
  command: airflow db init
  # Args to use when running the migrate database job (templated).