airflow:
  executor: "KubernetesExecutor"
  images:
    airflow:
      repository: apache/airflow
      # tag: v1.0.0 
      pullPolicy: Always
    createUserJob:
      useHelmHooks: false
      applyCustomEnv: false
    migrateDatabaseJob:
      useHelmHooks: false
      applyCustomEnv: false