executor: "KubernetesExecutor"
image:
  airflow:
    repository: vantuan12345/airlake:v1.0.0
    tag: latest
    ## WARNING: even if set to "Always" DO NOT reuse tag names, 
    ##          containers only pull the latest image when restarting
    pullPolicy: IfNotPresent
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
  jobAnnotations:
        "argocd.argoproj.io/hook": Sync